{% set version = "0.82" %}

package:
  name: pybufr-ecmwf
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pybufr-ecmwf/pybufr-ecmwf-{{ version }}.tar.gz
  sha256: 3f8375f2ced161a203c3521520fdeb8b8b5b088987c98b609abdff7408b78a4c

build:
  number: 1001
  skip: True  # [win]
  script:
    - export DYLD_FALLBACK_LIBRARY_PATH=$PREFIX/lib  # [osx]
    - export LDFLAGS="-undefined dynamic_lookup -bundle"  # [osx]
    - python setup.py install

requirements:
  build:
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pybufr_ecmwf

about:
  home: https://github.com/jdkloe/pybufr-ecmwf
  license: LGPL-3.0
  summary: 'Python interface around the ECMWF-BUFR library.'
  description: |
    A Python module that allows reading and writing BUFR formatted files, where
    BUFR stands for Binary Universal Form for the Representation of
    meteorological data.
  dev_url: https://github.com/jdkloe/pybufr-ecmwf

extra:
  recipe-maintainers:
    - cpaulik
    - ocefpaf
