{% set version = "0.82" %}
{% set sha256 = "3f8375f2ced161a203c3521520fdeb8b8b5b088987c98b609abdff7408b78a4c" %}

package:
  name: pybufr-ecmwf
  version: {{ version }}

source:
  fn: pybufr-ecmwf-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pybufr-ecmwf/pybufr-ecmwf-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  script:
    - export DYLD_FALLBACK_LIBRARY_PATH=$PREFIX/lib  # [osx]
    - export LDFLAGS="-undefined dynamic_lookup -bundle"  # [osx]
    - "{{ PYTHON }} setup.py install"
  skip: True  # [win]

requirements:
  build:
    - python
    - numpy
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - pip
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - libgcc  # [linux]
    - libgfortran  # [osx]

test:
  imports:
    - pybufr_ecmwf
  commands:
    - conda inspect linkages -p $PREFIX pybufr-ecmwf  # [not win]
    - conda inspect objects -p $PREFIX pybufr-ecmwf  # [osx]

about:
  home: https://github.com/jdkloe/pybufr-ecmwf
  license: LGPL-3.0-only
  license_file: LICENSE.txt
  summary: 'Python interface around the ECMWF-BUFR library.'
  description: |
    A Python module that allows reading and writing BUFR formatted files, where
    BUFR stands for Binary Universal Form for the Representation of
    meteorological data.
  dev_url: https://github.com/jdkloe/pybufr-ecmwf

extra:
  recipe-maintainers:
    - akrherz
    - cpaulik
    - ocefpaf
