travis:
  secure:
    BINSTAR_TOKEN: rItdyL3EXWCToYhPmoo+Arg29nDAYGaR61ROkVzyCZ4y1SjlgcgsL6mgnwwJ/SH5DMVkQpnmW66aHSQ6YUJVVBJKw9isqLE1YexFQJKnXBMQedTlTXsrwL03Sih7iQTU5SPwWVLBVZV7oEyYQf5Lu6Ryw2EA6uRfCR61kw9hFLJxMklCrZKbymwjD4baMs4N1zv+IdMvGmKS9RwDo7qlgHsltXsPL38uaNwajsZOQ6vJ9JzorDkg+RS1YWW15zxvkHXm8KY7lIVZzN5bo3spS1UqXfQwj5oiN1PZMWPW/UmF+qs4YoyiUrS/HAbZQWYcZzQ15ATQkIjQKJP09JUFj9HRJfZi3wcrQxIdAkMaAtjUr0ev1g8k9eZVg1AJoB80MB3QYYJxlZ9qBb5HB8NofMjIjOVAahK3oerJX9M0Kgu50jRzHYs4hijA4u4NbQ4lO41AWL0X+o75QzPGK1OD31yH365q8jnIeOoYKD6fCQE9mEi1Jtq6H2e0k++tb6Xh7jcN7bNzbDinAOa5bXTVFOESzLnXT3q1ek0UI/85jZHom6uWJpH3PFlBRYrl764uUMYZbAbq+bLbIb1MW4n6Nk/v1BnRQQwrxXpwUW2AN0yxKitJ8TarCzwXNkLBHAeyCbRFW6AfRJIS1T56Ay6CQ1Gaq+PZ3WLlbJILZZvYQEs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
